name: Build iOS IPA
on: [push]

jobs:
  build-ios:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Unzip source
      run: unzip YetAnotherPixelDungeon*.zip
    
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Build IPA
      run: |
        cd YetAnotherPixelDungeon-*
        chmod +x gradlew
        ./gradlew ios:createIPA
    
    - name: Upload IPA
      uses: actions/upload-artifact@v4
      with:
        name: YAPD-iOS
        path: |
          YetAnotherPixelDungeon-*/ios/build/robovm/*.ipa
